CREATE TABLE users (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 email VARCHAR(254) NOT NULL UNIQUE, username VARCHAR(32) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, email_verified_at DATETIME(6) NULL,
 platform_role ENUM('PLAYER','SUPER_ADMIN') NOT NULL DEFAULT 'PLAYER',
 disabled_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE user_profiles (
 user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 player_id VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 display_name VARCHAR(80) NOT NULL, avatar_url VARCHAR(500) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE sessions (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 expires_at DATETIME(6) NOT NULL, revoked_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX(user_id,revoked_at), INDEX(expires_at)
) ENGINE=InnoDB;
CREATE TABLE account_tokens (
 token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 purpose ENUM('VERIFY_EMAIL','RESET_PASSWORD') NOT NULL,
 expires_at DATETIME(6) NOT NULL, consumed_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX(user_id,purpose), INDEX(expires_at)
) ENGINE=InnoDB;
CREATE TABLE leagues (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 name VARCHAR(100) NOT NULL, visibility ENUM('PUBLIC','PRIVATE') NOT NULL,
 created_by CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 FOREIGN KEY(created_by) REFERENCES users(id), INDEX(visibility,created_at)
) ENGINE=InnoDB;
CREATE TABLE league_members (
 league_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 role ENUM('LEAGUE_ADMIN','MEMBER') NOT NULL DEFAULT 'MEMBER',
 status ENUM('ACTIVE','REMOVED') NOT NULL DEFAULT 'ACTIVE',
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 PRIMARY KEY(league_id,user_id), FOREIGN KEY(league_id) REFERENCES leagues(id),
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX(user_id,status)
) ENGINE=InnoDB;
CREATE TABLE rulesets (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 name VARCHAR(80) NOT NULL UNIQUE,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE ruleset_versions (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 ruleset_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 version INT UNSIGNED NOT NULL, engine_version VARCHAR(32) NOT NULL,
 content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 configuration JSON NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 FOREIGN KEY(ruleset_id) REFERENCES rulesets(id), UNIQUE(ruleset_id,version)
) ENGINE=InnoDB;
CREATE TABLE audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 actor_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 league_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
 action VARCHAR(64) NOT NULL, entity_type VARCHAR(64) NOT NULL,
 entity_id VARCHAR(64) NOT NULL, old_value JSON NULL,new_value JSON NULL,reason VARCHAR(1000) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 FOREIGN KEY(actor_id) REFERENCES users(id), FOREIGN KEY(league_id) REFERENCES leagues(id),
 INDEX(league_id,created_at),INDEX(entity_type,entity_id,id)
) ENGINE=InnoDB;
CREATE TABLE outbox_events (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 kind VARCHAR(64) NOT NULL, payload JSON NOT NULL,
 deduplication_key VARCHAR(150) NOT NULL UNIQUE,
 attempts INT UNSIGNED NOT NULL DEFAULT 0, available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 delivered_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 INDEX(delivered_at,available_at)
) ENGINE=InnoDB;
